series: Basic OpenGL with GLFW
title: 3D Cameras
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use a 3d camera to move objects into view.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: 2D Cameras